#include "lifter.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <fmt/core.h>
#include <fmt/format.h>

#include "lib/m68k/instruction/instruction.h"
#include "lib/m68k/target/target.h"

namespace fs = std::filesystem;
using IK = m68k::Instruction::Kind;
using IS = m68k::Instruction::Size;
using IC = m68k::Instruction::Condition;
using TK = m68k::Target::Kind;

// ─────────────────────────────────────────────────────────────────────────────

Lifter::Lifter(const std::vector<uint8_t>& rom, const RecompConfig& cfg,
               const std::map<uint32_t, RecompFunction>& functions)
    : rom_(rom), cfg_(cfg), functions_(functions) {}

// ─────────────────────────────────────────────────────────────────────────────

void Lifter::emit() {
    fs::create_directories(cfg_.output_dir);

    // func_table.h — forward declarations
    {
        std::ofstream out(cfg_.output_dir + "/func_table.h");
        out << "// Generated by smd_recomp — DO NOT EDIT\n"
               "#pragma once\n"
               "#include \"recomp_runtime.h\"\n\n"
               "namespace " << cfg_.namespace_name << " {\n\n";
        for (const auto& [addr, func] : functions_)
            out << fmt::format("void {}(RecompContext& ctx);\n", func.name);
        out << "\n} // namespace " << cfg_.namespace_name << "\n\n"
               "// Initialise dispatch table\nvoid recomp_init();\n";
    }

    // func_table.cpp — address → function pointer dispatch
    {
        std::ofstream out(cfg_.output_dir + "/func_table.cpp");
        out << "// Generated by smd_recomp — DO NOT EDIT\n"
               "#include \"func_table.h\"\n"
               "#include <unordered_map>\n\n"
               "static std::unordered_map<uint32_t, RecompFunc> s_table = {\n";
        for (const auto& [addr, func] : functions_)
            out << fmt::format("    {{ 0x{:08X}U, &{}::{} }},\n",
                               addr, cfg_.namespace_name, func.name);
        out << "};\n\n"
               "void recomp_call_addr(uint32_t addr, RecompContext& ctx) {\n"
               "    auto it = s_table.find(addr);\n"
               "    if (it != s_table.end()) it->second(ctx);\n"
               "    // else: unresolved indirect call — implement fallback if needed\n"
               "}\n\n"
               "void recomp_init() { /* dispatch table is statically initialised */ }\n";
    }

    if (cfg_.split_files) {
        // One .cpp per function
        for (const auto& [addr, func] : functions_) {
            std::string src = emit_function(func);
            std::ofstream out(cfg_.output_dir + "/" + func.name + ".cpp");
            out << src;
        }
    } else {
        // All functions in one .cpp
        std::ofstream out(cfg_.output_dir + "/all_functions.cpp");
        out << "// Generated by smd_recomp — DO NOT EDIT\n"
               "#include \"recomp_runtime.h\"\n"
               "#include \"func_table.h\"\n\n"
               "namespace " << cfg_.namespace_name << " {\n\n";
        for (const auto& [addr, func] : functions_)
            out << emit_function(func);
        out << "} // namespace " << cfg_.namespace_name << "\n";
    }
}

// ─────────────────────────────────────────────────────────────────────────────

std::string Lifter::emit_function(const RecompFunction& func) const {
    std::ostringstream s;
    if (cfg_.split_files) {
        s << "// Generated by smd_recomp — DO NOT EDIT\n"
          << "#include \"recomp_runtime.h\"\n"
          << "#include \"func_table.h\"\n\n"
          << "namespace " << cfg_.namespace_name << " {\n\n";
    }

    s << fmt::format("void {}(RecompContext& ctx) {{\n", func.name);
    if (!func.blocks.empty())
        s << fmt::format("  goto lbl_{:06X};\n\n", func.entry_addr);

    for (const auto& [addr, block] : func.blocks) {
        s << fmt::format("lbl_{:06X}:\n", addr);
        s << emit_block(block, func);
        s << "\n";
    }

    s << "}\n\n";
    if (cfg_.split_files)
        s << "} // namespace " << cfg_.namespace_name << "\n";
    return s.str();
}

// ─────────────────────────────────────────────────────────────────────────────

std::string Lifter::emit_block(const BasicBlock& block, const RecompFunction& func) const {
    std::ostringstream s;

    // Emit all instructions except the terminator
    // The terminator is the last instruction if it's a branch/return.
    for (const auto& di : block.insts) {
        s << "  // " << di.inst.print()
          << fmt::format(" @ {:06X}\n", di.pc_before);
        s << translate_inst(di);
    }

    // Emit block exit
    switch (block.exit) {
    case BlockExit::Return:
        // RTS/RTE/RTR already handled in translate_inst
        break;
    case BlockExit::Fallthrough:
        s << fmt::format("  goto lbl_{:06X};\n", block.fallthrough);
        break;
    case BlockExit::Jump:
        if (block.branch_target && functions_.count(block.branch_target) &&
            block.branch_target != func.entry_addr) {
            // Tail call to another function
            s << fmt::format("  {}::{}(ctx); return;\n",
                             cfg_.namespace_name,
                             functions_.at(block.branch_target).name);
        } else if (block.branch_target) {
            s << fmt::format("  goto lbl_{:06X};\n", block.branch_target);
        }
        break;
    case BlockExit::Branch:
        // Last instruction was Bcc — the goto was already emitted in translate_inst
        break;
    case BlockExit::Call:
    case BlockExit::IndirectCall:
        // Call was emitted in translate_inst; now fall through
        s << fmt::format("  goto lbl_{:06X};\n", block.fallthrough);
        break;
    case BlockExit::IndirectJump:
        // Jump code emitted in translate_inst
        break;
    }
    return s.str();
}

// ─────────────────────────────────────────────────────────────────────────────
// Instruction translation
// ─────────────────────────────────────────────────────────────────────────────

std::string Lifter::translate_inst(const DecodedInst& di) const {
    const auto& inst = di.inst;
    const int bytes  = inst.get_size(); // 1, 2, or 4
    const auto kind  = inst.get_kind();

    // Helpers capturing di
    auto rs = [&]() { return read_operand(inst.get_src(), di.src_ea, bytes); };
    auto rd = [&]() { return read_operand(inst.get_dst(), di.dst_ea, bytes); };
    auto ws = [&](const std::string& v) {
        return write_operand(inst.get_src(), di.src_ea, bytes, v);
    };
    auto wd = [&](const std::string& v) {
        return write_operand(inst.get_dst(), di.dst_ea, bytes, v);
    };
    auto pre_s  = [&]() { return pre_effect(inst.get_src(), bytes); };
    auto post_s = [&]() { return post_effect(inst.get_src(), bytes); };
    auto pre_d  = [&]() { return pre_effect(inst.get_dst(), bytes); };
    auto post_d = [&]() { return post_effect(inst.get_dst(), bytes); };

    const int N = inst.get_has_dst() ? inst.get_dst().index() : 0;
    const int M = inst.get_has_src() ? inst.get_src().index() : 0;
    const uint32_t data = inst.get_data();

    std::ostringstream out;
    const auto line = [&](const std::string& s) { out << "  " << s << "\n"; };

    switch (kind) {

    // ── NOP ──────────────────────────────────────────────────────────────────
    case IK::NopKind:
    case IK::ResetKind:
        break;

    // ── MOVE ─────────────────────────────────────────────────────────────────
    case IK::MoveKind:
        line(fmt::format("{{ {}uint32_t _v = {}; {}m68k_flags_move(ctx.sr, _v, {}); }}",
                         pre_s(), rs(), wd("_v") + post_s(), bytes));
        break;

    case IK::MoveaKind: {
        // Sign-extend word to long for .w size
        std::string src_expr = (bytes == 2)
            ? fmt::format("(uint32_t)(int32_t)(int16_t)({})", rs())
            : rs();
        line(fmt::format("{{ {}uint32_t _v = {}; ctx.a[{}] = _v; {}}}",
                         pre_s(), src_expr, N, post_s()));
        break;
    }

    case IK::MoveqKind:
        line(fmt::format("{{ ctx.d[{}] = (uint32_t)(int32_t)(int8_t)0x{:02X}U;"
                         " m68k_flags_move(ctx.sr, ctx.d[{}], 4); }}",
                         N, data & 0xFF, N));
        break;

    case IK::MoveFromSrKind:
        line(fmt::format("{{ {}{}{}}}",
                         pre_d(), wd("(uint32_t)(uint16_t)ctx.sr"), post_d()));
        break;

    case IK::MoveToSrKind:
        line(fmt::format("{{ {}ctx.sr = (uint16_t)({}); {}}}",
                         pre_s(), rs(), post_s()));
        break;

    case IK::MoveToCcrKind:
        line(fmt::format("{{ {}ctx.sr &= 0xFF00U; ctx.sr |= ({}) & 0xFFU; {}}}",
                         pre_s(), rs(), post_s()));
        break;

    case IK::MoveFromUspKind:
        line(fmt::format("{{ {}{}{}}}",
                         pre_d(), wd("ctx.usp"), post_d()));
        break;

    case IK::MoveToUspKind:
        line(fmt::format("{{ {}ctx.usp = {}; {}}}",
                         pre_s(), rs(), post_s()));
        break;

    // ── MOVEM ────────────────────────────────────────────────────────────────
    case IK::MovemKind: {
        const uint32_t mask = data;
        const bool load = inst.get_has_src();
        const auto& ea_tgt = load ? inst.get_src() : inst.get_dst();
        const uint32_t ea_val = load ? di.src_ea : di.dst_ea;
        const int idx = ea_tgt.index();

        // Helper: register name for bit position in mask
        // load mode:  bit 0=D0, 1=D1 ... 7=D7, 8=A0 ... 15=A7
        // store predecrement: bit 15=D0 ... 8=D7, 7=A0 ... 0=A7
        const bool predec = !load && ea_tgt.kind() == TK::AddressDecrementKind;
        const bool postinc = load && ea_tgt.kind() == TK::AddressIncrementKind;

        auto reg_for_bit = [&](int bit) -> std::string {
            int i = predec ? (15 - bit) : bit;
            if (i < 8) return fmt::format("ctx.d[{}]", i);
            if (i < 15) return fmt::format("ctx.a[{}]", i - 8);
            return "ctx.a[7]";
        };

        // Count set bits
        int cnt = 0;
        for (int b = 0; b < 16; ++b) if ((mask >> b) & 1) ++cnt;

        out << "  {\n";
        if (load) {
            // Memory → registers
            std::string addr_expr = (ea_tgt.kind() == TK::AddressKind ||
                                     ea_tgt.kind() == TK::AddressIncrementKind)
                ? fmt::format("ctx.a[{}]", idx)
                : (ea_val ? fmt::format("0x{:06X}U", ea_val)
                          : ea_expr(ea_tgt, ea_val, di.pc_after));
            out << fmt::format("    uint32_t _a = {};\n", addr_expr);
            int offset = 0;
            for (int b = 0; b < 16; ++b) {
                if (!((mask >> b) & 1)) continue;
                std::string reg = reg_for_bit(b);
                // Skip write if it's the postincrement register
                bool skip_write = postinc && b >= 8 && (b - 8) == idx;
                if (bytes == 4) {
                    if (!skip_write)
                        out << fmt::format("    {} = recomp_mem_read32(_a + {});\n", reg, offset);
                    else
                        out << fmt::format("    /* skip write to postinc A{} */\n", idx);
                    offset += 4;
                } else {
                    if (!skip_write)
                        out << fmt::format("    {} = (uint32_t)(int32_t)(int16_t)recomp_mem_read16(_a + {});\n",
                                           reg, offset);
                    else
                        out << fmt::format("    /* skip write to postinc A{} */\n", idx);
                    offset += 2;
                }
            }
            if (postinc)
                out << fmt::format("    ctx.a[{}] = _a + {};\n", idx, cnt * bytes);
        } else {
            // Registers → memory (predecrement or fixed EA)
            if (predec) {
                out << fmt::format("    ctx.a[{}] -= {};\n", idx, cnt * bytes);
                out << fmt::format("    uint32_t _a = ctx.a[{}];\n", idx);
            } else {
                std::string addr_expr = ea_val
                    ? fmt::format("0x{:06X}U", ea_val)
                    : ea_expr(ea_tgt, ea_val, di.pc_after);
                out << fmt::format("    uint32_t _a = {};\n", addr_expr);
            }
            int offset = 0;
            for (int b = 0; b < 16; ++b) {
                if (!((mask >> b) & 1)) continue;
                std::string reg = reg_for_bit(b);
                if (bytes == 4) {
                    out << fmt::format("    recomp_mem_write32(_a + {}, {});\n", offset, reg);
                    offset += 4;
                } else {
                    out << fmt::format("    recomp_mem_write16(_a + {}, (uint16_t)({}));\n", offset, reg);
                    offset += 2;
                }
            }
        }
        out << "  }\n";
        break;
    }

    // ── SWAP ─────────────────────────────────────────────────────────────────
    case IK::SwapKind:
        line(fmt::format("{{ ctx.d[{0}] = (ctx.d[{0}] >> 16) | (ctx.d[{0}] << 16);"
                         " m68k_flags_move(ctx.sr, ctx.d[{0}], 4); }}", N));
        break;

    // ── EXG ──────────────────────────────────────────────────────────────────
    case IK::ExgKind: {
        std::string s_expr = (inst.get_src().kind() == TK::DataRegisterKind)
                             ? fmt::format("ctx.d[{}]", M)
                             : fmt::format("ctx.a[{}]", M);
        std::string d_expr = (inst.get_dst().kind() == TK::DataRegisterKind)
                             ? fmt::format("ctx.d[{}]", N)
                             : fmt::format("ctx.a[{}]", N);
        line(fmt::format("{{ uint32_t _t = {0}; {0} = {1}; {1} = _t; }}", s_expr, d_expr));
        break;
    }

    // ── EXT ──────────────────────────────────────────────────────────────────
    case IK::ExtKind:
        line(fmt::format("ctx.d[{}] = m68k_ext(ctx.sr, ctx.d[{}], {});", N, N, bytes));
        break;

    // ── ADD / SUB / AND / OR / EOR ───────────────────────────────────────────
    case IK::AddKind: case IK::AddiKind: {
        line(fmt::format("{{ {}uint32_t _r = m68k_add(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;
    }
    case IK::AddaKind: {
        const std::string src = (bytes == 2)
            ? fmt::format("(uint32_t)(int32_t)(int16_t)({})", rs())
            : rs();
        line(fmt::format("{{ {}ctx.a[{}] += {}; {}}}",
                         pre_s(), N, src, post_s()));
        break;
    }
    case IK::AddqKind: {
        uint32_t imm = data ? data : 8;
        if (inst.get_dst().kind() == TK::AddressRegisterKind)
            line(fmt::format("ctx.a[{}] += {}U;", N, imm));
        else
            line(fmt::format("{{ {}uint32_t _r = m68k_add(ctx.sr, {}, {}U, {}); {}{}}}",
                             pre_d(), rd(), imm, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::AddxKind:
        line(fmt::format("{{ {}{}uint32_t _r = m68k_addx(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;

    case IK::SubKind: case IK::SubiKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_sub(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;
    case IK::SubaKind: {
        const std::string src = (bytes == 2)
            ? fmt::format("(uint32_t)(int32_t)(int16_t)({})", rs())
            : rs();
        line(fmt::format("{{ {}ctx.a[{}] -= {}; {}}}",
                         pre_s(), N, src, post_s()));
        break;
    }
    case IK::SubqKind: {
        uint32_t imm = data ? data : 8;
        if (inst.get_dst().kind() == TK::AddressRegisterKind)
            line(fmt::format("ctx.a[{}] -= {}U;", N, imm));
        else
            line(fmt::format("{{ {}uint32_t _r = m68k_sub(ctx.sr, {}, {}U, {}); {}{}}}",
                             pre_d(), rd(), imm, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::SubxKind:
        line(fmt::format("{{ {}{}uint32_t _r = m68k_subx(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;

    case IK::AndKind: case IK::AndiKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_and(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;
    case IK::OrKind: case IK::OriKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_or(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;
    case IK::EorKind: case IK::EoriKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_eor(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_s(), rd(), rs(), bytes, wd("_r"), post_d()));
        break;

    case IK::AndiToCcrKind:
        line(fmt::format("ctx.sr &= (uint16_t)(({}) | 0xFF00U);", rs()));
        break;
    case IK::OriToCcrKind:
        line(fmt::format("ctx.sr |= (uint16_t)(({}) & 0x00FFU);", rs()));
        break;
    case IK::EoriToCcrKind:
        line(fmt::format("ctx.sr = (uint16_t)((uint16_t)ctx.sr ^ (({})) & 0x00FFU);", rs()));
        break;
    case IK::AndiToSrKind:
        line(fmt::format("ctx.sr &= (uint16_t)(({}) & 0xA7FFU);", rs()));
        break;
    case IK::OriToSrKind:
        line(fmt::format("ctx.sr |= (uint16_t)(({}) & 0xA7FFU);", rs()));
        break;
    case IK::EoriToSrKind:
        line(fmt::format("ctx.sr = (uint16_t)((uint16_t)ctx.sr ^ (({})) & 0xA7FFU);", rs()));
        break;

    // ── CMP ──────────────────────────────────────────────────────────────────
    case IK::CmpKind: case IK::CmpiKind: case IK::CmpmKind:
        line(fmt::format("{{ {}m68k_cmp(ctx.sr, {}, {}, {}); {}}}",
                         pre_s(), rd(), rs(), bytes, post_s()));
        break;
    case IK::CmpaKind:
        line(fmt::format("{{ {}m68k_cmpa(ctx.sr, ctx.a[{}], {}, {}); {}}}",
                         pre_s(), N, rs(), bytes, post_s()));
        break;

    // ── NEG / NOT / CLR / NEGX ───────────────────────────────────────────────
    case IK::NegKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_neg(ctx.sr, {}, {}); {}{}}}",
                         pre_d(), rd(), bytes, wd("_r"), post_d()));
        break;
    case IK::NegxKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_negx(ctx.sr, {}, {}); {}{}}}",
                         pre_d(), rd(), bytes, wd("_r"), post_d()));
        break;
    case IK::NotKind:
        line(fmt::format("{{ {}uint32_t _r = m68k_not(ctx.sr, {}, {}); {}{}}}",
                         pre_d(), rd(), bytes, wd("_r"), post_d()));
        break;
    case IK::ClrKind:
        line(fmt::format("{{ {}{}ctx.sr.n = false; ctx.sr.z = true; ctx.sr.v = false; ctx.sr.c = false; }}",
                         pre_d(), wd("0U") + post_d()));
        break;

    // ── MUL / DIV ────────────────────────────────────────────────────────────
    case IK::MuluKind:
        line(fmt::format("{{ {}ctx.d[{}] = m68k_mulu(ctx.sr, ctx.d[{}], {}); {}}}",
                         pre_s(), N, N, rs(), post_s()));
        break;
    case IK::MulsKind:
        line(fmt::format("{{ {}ctx.d[{}] = m68k_muls(ctx.sr, ctx.d[{}], {}); {}}}",
                         pre_s(), N, N, rs(), post_s()));
        break;
    case IK::DivuKind:
        line(fmt::format("{{ {}ctx.d[{}] = m68k_divu(ctx.sr, ctx.d[{}], {}); {}}}",
                         pre_s(), N, N, rs(), post_s()));
        break;
    case IK::DivsKind:
        line(fmt::format("{{ {}ctx.d[{}] = m68k_divs(ctx.sr, ctx.d[{}], {}); {}}}",
                         pre_s(), N, N, rs(), post_s()));
        break;

    // ── SHIFTS ───────────────────────────────────────────────────────────────
    case IK::AslKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_asl(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::AsrKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_asr(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::LslKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_lsl(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::LsrKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_lsr(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::RolKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_rol(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::RorKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_ror(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::RoxlKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_roxl(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }
    case IK::RoxrKind: {
        std::string cnt = inst.get_has_src()
            ? fmt::format("({}) & 63U", rs())
            : fmt::format("{}U", data ? data : 8);
        line(fmt::format("{{ {}uint32_t _r = m68k_roxr(ctx.sr, {}, {}, {}); {}{}}}",
                         pre_d(), rd(), cnt, bytes, wd("_r"), post_d()));
        break;
    }

    // ── BIT INSTRUCTIONS ─────────────────────────────────────────────────────
    case IK::BtstKind: case IK::BchgKind: case IK::BclrKind: case IK::BsetKind: {
        bool is_dreg = inst.get_dst().kind() == TK::DataRegisterKind;
        std::string mod = is_dreg ? "32" : "8";
        out << "  {\n";
        out << fmt::format("    {}uint32_t _bn = ({}) % {}U;\n", pre_s(), rs(), mod);
        if (is_dreg)
            out << fmt::format("    uint32_t _dv = ctx.d[{}];\n", N);
        else
            out << fmt::format("    {}uint32_t _dv = {};\n", pre_d(), rd());
        out << "    uint32_t _mask = 1U << _bn;\n";
        out << "    ctx.sr.z = !(_dv & _mask);\n";
        if (kind == IK::BchgKind)
            out << "    uint32_t _nv = _dv ^ _mask;\n";
        else if (kind == IK::BclrKind)
            out << "    uint32_t _nv = _dv & ~_mask;\n";
        else if (kind == IK::BsetKind)
            out << "    uint32_t _nv = _dv | _mask;\n";
        if (kind != IK::BtstKind) {
            if (is_dreg)
                out << fmt::format("    ctx.d[{}] = _nv;\n", N);
            else
                out << fmt::format("    {}{};\n", wd("_nv"), post_d());
        } else {
            if (!is_dreg) out << fmt::format("    {};\n", post_d());
        }
        out << fmt::format("    {};\n", post_s());
        out << "  }\n";
        break;
    }

    // ── Scc ──────────────────────────────────────────────────────────────────
    case IK::SccKind:
        line(fmt::format("{{ {}{}{}}}",
                         pre_d(),
                         wd(fmt::format("{} ? 0xFFU : 0x00U", cond_expr(inst.get_cond()))),
                         post_d()));
        break;

    // ── LEA ──────────────────────────────────────────────────────────────────
    case IK::LeaKind:
        line(fmt::format("ctx.a[{}] = {};",
                         N, ea_expr(inst.get_src(), di.src_ea, di.pc_after)));
        break;

    // ── PEA ──────────────────────────────────────────────────────────────────
    case IK::PeaKind:
        line(fmt::format("recomp_push32(ctx, {});",
                         ea_expr(inst.get_src(), di.src_ea, di.pc_after)));
        break;

    // ── LINK / UNLINK ────────────────────────────────────────────────────────
    case IK::LinkKind:
        line(fmt::format("{{ recomp_push32(ctx, ctx.a[{0}]); ctx.a[{0}] = ctx.a[7]; "
                         "ctx.a[7] += (int32_t)(int16_t)0x{1:04X}U; }}",
                         N, inst.get_src().get_ext_word0()));
        break;
    case IK::UnlinkKind:
        line(fmt::format("{{ ctx.a[7] = ctx.a[{0}]; ctx.a[{0}] = recomp_pop32(ctx); }}",
                         N));
        break;

    // ── CHK ──────────────────────────────────────────────────────────────────
    case IK::ChkKind:
        line(fmt::format("{{ {}int16_t _ub = (int16_t)({}); int16_t _v = (int16_t)(ctx.d[{}] & 0xFFFF);"
                         " ctx.sr.n = (_v < 0); if (_v < 0 || _v > _ub) recomp_trap(6U, ctx); {}}}",
                         pre_s(), rs(), N, post_s()));
        break;

    // ── TAS ──────────────────────────────────────────────────────────────────
    case IK::TasKind:
        line(fmt::format("{{ {}uint8_t _v = (uint8_t)({}); ctx.sr.n = (_v >> 7) & 1;"
                         " ctx.sr.z = (_v == 0); ctx.sr.v = false; ctx.sr.c = false;"
                         " {}{}}}",
                         pre_d(), rd(), wd("(uint32_t)(_v | 0x80U)"), post_d()));
        break;

    // ── TST ──────────────────────────────────────────────────────────────────
    case IK::TstKind:
        line(fmt::format("{{ {}m68k_flags_move(ctx.sr, {}, {}); {}}}",
                         pre_d(), rd(), bytes, post_d()));
        break;

    // ── ABCD / SBCD / NBCD ───────────────────────────────────────────────────
    case IK::AbcdKind: {
        out << "  {\n";
        out << fmt::format("    {}uint8_t _s = (uint8_t)({});\n", pre_s(), rs());
        out << fmt::format("    {}uint8_t _d = (uint8_t)({});\n", pre_d(), rd());
        out << "    uint8_t _x = ctx.sr.x ? 1 : 0;\n";
        out << "    uint32_t _br = _s + _d + _x;\n";
        out << "    bool _c = false;\n";
        out << "    int _lo = (_s & 0xF) + (_d & 0xF) + _x;\n";
        out << "    if (_lo > 9) { _c = true; _lo -= 10; }\n";
        out << "    int _hi = ((_s >> 4) & 0xF) + ((_d >> 4) & 0xF) + (_c ? 1 : 0); _c = false;\n";
        out << "    if (_lo >= 16) { _lo -= 16; ++_hi; }\n";
        out << "    if (_hi > 9) { _c = true; _hi -= 10; }\n";
        out << "    uint8_t _r = (uint8_t)(((_hi << 4) + _lo) & 0xFF);\n";
        out << fmt::format("    {}{};\n", wd("(uint32_t)_r"), post_d());
        out << "    ctx.sr.n = (_r >> 7) & 1;\n";
        out << "    ctx.sr.c = _c; ctx.sr.x = _c;\n";
        out << "    ctx.sr.v = (~_br & _r & 0x80) != 0;\n";
        out << "    if (_r != 0) ctx.sr.z = false;\n";
        out << fmt::format("    {};\n", post_s());
        out << "  }\n";
        break;
    }
    case IK::SbcdKind: {
        out << "  {\n";
        out << fmt::format("    {}uint8_t _s = (uint8_t)({});\n", pre_s(), rs());
        out << fmt::format("    {}uint8_t _d = (uint8_t)({});\n", pre_d(), rd());
        out << "    uint8_t _x = ctx.sr.x ? 1 : 0;\n";
        out << "    uint32_t _br = _d - _s - _x;\n";
        out << "    bool _c = false;\n";
        out << "    int _lo = (_d & 0xF) - (_s & 0xF) - _x;\n";
        out << "    if (_lo < 0) { _c = true; _lo += 10; }\n";
        out << "    int _hi = ((_d>>4)&0xF) - ((_s>>4)&0xF) - (_c?1:0); _c = false;\n";
        out << "    if (_hi < 0) { _c = true; _hi += 10; }\n";
        out << "    if (_hi == 0 && _lo < 0) _c = true;\n";
        out << "    uint8_t _r = (uint8_t)(((_hi << 4) + _lo) & 0xFF);\n";
        out << fmt::format("    {}{};\n", wd("(uint32_t)_r"), post_d());
        out << "    ctx.sr.n = (_r >> 7) & 1; ctx.sr.c = _c; ctx.sr.x = _c;\n";
        out << "    ctx.sr.v = (_br & ~_r & 0x80) != 0;\n";
        out << "    if (_r != 0) ctx.sr.z = false;\n";
        out << fmt::format("    {};\n", post_s());
        out << "  }\n";
        break;
    }
    case IK::NbcdKind: {
        out << "  {\n";
        out << fmt::format("    {}uint8_t _d = (uint8_t)({});\n", pre_d(), rd());
        out << "    uint8_t _x = ctx.sr.x ? 1 : 0;\n";
        out << "    uint32_t _br = (uint32_t)0 - _d - _x;\n";
        out << "    bool _c = false;\n";
        out << "    int _lo = 0 - (_d & 0xF) - _x;\n";
        out << "    if (_lo < 0) { _c = true; _lo += 10; }\n";
        out << "    int _hi = 0 - ((_d>>4)&0xF) - (_c?1:0); _c = false;\n";
        out << "    if (_hi < 0) { _c = true; _hi += 10; }\n";
        out << "    uint8_t _r = (uint8_t)(((_hi << 4) + _lo) & 0xFF);\n";
        out << fmt::format("    {}{};\n", wd("(uint32_t)_r"), post_d());
        out << "    ctx.sr.n = (_r >> 7) & 1; ctx.sr.c = _c; ctx.sr.x = _c;\n";
        out << "    ctx.sr.v = (~_br & _r & 0x80) != 0;\n";
        out << "    if (_r != 0) ctx.sr.z = false;\n";
        out << fmt::format("    {};\n", post_d());
        out << "  }\n";
        break;
    }

    // ── MOVEP ────────────────────────────────────────────────────────────────
    case IK::MovepKind: {
        // Simplified: emit a runtime call comment (uncommon instruction)
        line("/* MOVEP — skipping (rare, implement if needed) */");
        break;
    }

    // ── BRANCHES (handled at block level but emit cond for Bcc) ──────────────
    case IK::BccKind: {
        const uint32_t tgt = (uint32_t)((int32_t)(di.pc_before + 2) +
            ((inst.get_size() == IS::ByteSize)
             ? (int32_t)(int8_t)(data & 0xFF)
             : (int32_t)(int16_t)(data & 0xFFFF)));
        if (inst.get_cond() == IC::TrueCond) {
            line(fmt::format("goto lbl_{:06X};", tgt));
        } else if (inst.get_cond() == IC::FalseCond) {
            // Never branch
        } else {
            line(fmt::format("if ({}) goto lbl_{:06X};", cond_expr(inst.get_cond()), tgt));
        }
        break;
    }

    case IK::DbccKind: {
        const uint32_t tgt = (uint32_t)((int32_t)(di.pc_before + 2) +
            (int32_t)(int16_t)(data & 0xFFFF));
        out << "  {\n";
        if (inst.get_cond() != IC::TrueCond) {
            out << fmt::format("    if (!({}))\n    {{\n", cond_expr(inst.get_cond()));
        }
        out << fmt::format("      uint16_t _cnt = (uint16_t)(ctx.d[{}] & 0xFFFF) - 1U;\n", N);
        out << fmt::format("      ctx.d[{}] = (ctx.d[{}] & 0xFFFF0000U) | _cnt;\n", N, N);
        out << fmt::format("      if ((int16_t)_cnt != -1) goto lbl_{:06X};\n", tgt);
        if (inst.get_cond() != IC::TrueCond) out << "    }\n";
        out << "  }\n";
        break;
    }

    // ── BSR (call) ───────────────────────────────────────────────────────────
    case IK::BsrKind: {
        const uint32_t tgt = (uint32_t)((int32_t)(di.pc_before + 2) +
            ((inst.get_size() == IS::ByteSize)
             ? (int32_t)(int8_t)(data & 0xFF)
             : (int32_t)(int16_t)(data & 0xFFFF)));
        line(fmt::format("recomp_push32(ctx, 0x{:06X}U); // BSR return addr", di.pc_after));
        if (functions_.count(tgt))
            line(fmt::format("{}::{}(ctx);",
                             cfg_.namespace_name, functions_.at(tgt).name));
        else
            line(fmt::format("recomp_call_addr(0x{:06X}U, ctx);", tgt));
        break;
    }

    // ── JSR ──────────────────────────────────────────────────────────────────
    case IK::JsrKind: {
        uint32_t tgt = static_ea(inst.get_dst(), di.pc_after);
        if (tgt == 0) {
            // Indirect call
            line(fmt::format("recomp_push32(ctx, 0x{:06X}U);", di.pc_after));
            line(fmt::format("recomp_call_addr({}, ctx);",
                             ea_expr(inst.get_dst(), di.dst_ea, di.pc_after)));
        } else {
            line(fmt::format("recomp_push32(ctx, 0x{:06X}U);", di.pc_after));
            if (functions_.count(tgt))
                line(fmt::format("{}::{}(ctx);",
                                 cfg_.namespace_name, functions_.at(tgt).name));
            else
                line(fmt::format("recomp_call_addr(0x{:06X}U, ctx);", tgt));
        }
        break;
    }

    // ── JMP ──────────────────────────────────────────────────────────────────
    case IK::JmpKind: {
        uint32_t tgt = static_ea(inst.get_dst(), di.pc_after);
        if (tgt) {
            if (functions_.count(tgt) && tgt != 0) {
                // Tail call
                line(fmt::format("{}::{}(ctx); return;",
                                 cfg_.namespace_name, functions_.at(tgt).name));
            } else {
                line(fmt::format("goto lbl_{:06X};", tgt));
            }
        } else {
            // Indirect jump — call the dispatcher
            line(fmt::format("recomp_call_addr({} & 0xFFFFFFU, ctx); return;",
                             ea_expr(inst.get_dst(), di.dst_ea, di.pc_after)));
        }
        break;
    }

    // ── RTS / RTE / RTR ──────────────────────────────────────────────────────
    case IK::RtsKind:
        line("{ uint32_t _ret = recomp_pop32(ctx); (void)_ret; return; }");
        break;
    case IK::RteKind:
        line("{ uint16_t _sr = recomp_pop16(ctx); ctx.a[7] += 2; "
             "uint32_t _pc = recomp_pop32(ctx); (void)_pc; ctx.sr = _sr; return; }");
        break;
    case IK::RtrKind:
        line("{ uint16_t _ccr = recomp_pop16(ctx); ctx.sr &= 0xFF00U; ctx.sr |= _ccr & 0xFFU; "
             "uint32_t _pc = recomp_pop32(ctx); (void)_pc; return; }");
        break;

    // ── TRAP ─────────────────────────────────────────────────────────────────
    case IK::TrapKind:
        line(fmt::format("recomp_trap({}U + 32U, ctx);", data & 0xF));
        break;
    case IK::TrapvKind:
        line("if (ctx.sr.v) recomp_trap(7U, ctx);");
        break;

    default:
        line(fmt::format("/* UNIMPLEMENTED: {} */", inst.print()));
        break;
    }

    return out.str();
}

// ─────────────────────────────────────────────────────────────────────────────
// Operand helpers
// ─────────────────────────────────────────────────────────────────────────────

std::string Lifter::read_operand(const m68k::Target& t, uint32_t sea, int bytes) const {
    const int bits = bytes * 8;
    const int idx  = t.index();
    switch (t.kind()) {
    case TK::DataRegisterKind:
        return fmt::format("ctx.d[{}]", idx);
    case TK::AddressRegisterKind:
        return fmt::format("ctx.a[{}]", idx);
    case TK::AddressKind:
    case TK::AddressIncrementKind:
        return fmt::format("recomp_mem_read{}(ctx.a[{}] & 0xFFFFFFU)", bits, idx);
    case TK::AddressDecrementKind:
        return fmt::format("recomp_mem_read{}(ctx.a[{}] & 0xFFFFFFU)", bits, idx);
    case TK::AddressDisplacementKind:
        return fmt::format("recomp_mem_read{}((ctx.a[{}] + (int32_t)(int16_t)0x{:04X}U) & 0xFFFFFFU)",
                           bits, idx, t.get_ext_word0());
    case TK::AddressIndexKind: {
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7;
        bool an = (ew >> 15) & 1;
        bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        return fmt::format("recomp_mem_read{}((ctx.a[{}] + {}({}) + (int32_t){})"
                           " & 0xFFFFFFU)", bits, idx, xcast, xr, (int)d8);
    }
    case TK::ProgramCounterDisplacementKind:
    case TK::AbsoluteShortKind:
    case TK::AbsoluteLongKind:
        return fmt::format("recomp_mem_read{}(0x{:06X}U)", bits, sea);
    case TK::ProgramCounterIndexKind: {
        // base is static, Xn is runtime
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7;
        bool an = (ew >> 15) & 1;
        bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        // sea holds pc_after - 2 ... but we reuse static_ea which was pc_after-2+disp
        // Actually sea = static_ea = 0 for ProgramCounterIndexKind (set in analyzer)
        // We need pc_after - 2 as the base; but we don't have it here.
        // Fall back: emit a TODO comment with runtime dispatch.
        return fmt::format("recomp_mem_read{}((0x{:06X}U + {}({}) + (int32_t){}) & 0xFFFFFFU)",
                           bits, sea, xcast, xr, (int)d8);
    }
    case TK::ImmediateKind:
        return fmt::format("0x{:08X}U", rom_read(t.get_address(), bytes));
    default:
        return "0 /* unknown operand */";
    }
}

std::string Lifter::write_operand(const m68k::Target& t, uint32_t sea, int bytes,
                                   const std::string& val) const {
    const int bits = bytes * 8;
    const int idx  = t.index();
    const uint32_t upper_mask = (bytes == 4) ? 0 : (~0U << (bytes * 8));
    const uint32_t lower_mask = (bytes == 4) ? ~0U : ((1U << (bytes * 8)) - 1);

    switch (t.kind()) {
    case TK::DataRegisterKind:
        if (bytes == 4)
            return fmt::format("ctx.d[{}] = {};", idx, val);
        return fmt::format("ctx.d[{0}] = (ctx.d[{0}] & 0x{1:08X}U) | ({2} & 0x{3:08X}U);",
                           idx, upper_mask, val, lower_mask);
    case TK::AddressRegisterKind:
        if (bytes == 4)
            return fmt::format("ctx.a[{}] = {};", idx, val);
        return fmt::format("ctx.a[{0}] = (ctx.a[{0}] & 0x{1:08X}U) | ({2} & 0x{3:08X}U);",
                           idx, upper_mask, val, lower_mask);
    case TK::AddressKind:
    case TK::AddressIncrementKind:
    case TK::AddressDecrementKind:
        return fmt::format("recomp_mem_write{}(ctx.a[{}] & 0xFFFFFFU, (uint{}_t)({}));",
                           bits, idx, bits, val);
    case TK::AddressDisplacementKind:
        return fmt::format("recomp_mem_write{}((ctx.a[{}] + (int32_t)(int16_t)0x{:04X}U) & 0xFFFFFFU, (uint{}_t)({}));",
                           bits, idx, t.get_ext_word0(), bits, val);
    case TK::AddressIndexKind: {
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7;
        bool an = (ew >> 15) & 1;
        bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        return fmt::format("recomp_mem_write{}((ctx.a[{}] + {}({}) + (int32_t){}) & 0xFFFFFFU, (uint{}_t)({}));",
                           bits, idx, xcast, xr, (int)d8, bits, val);
    }
    case TK::ProgramCounterDisplacementKind:
    case TK::AbsoluteShortKind:
    case TK::AbsoluteLongKind:
        return fmt::format("recomp_mem_write{}(0x{:06X}U, (uint{}_t)({}));",
                           bits, sea, bits, val);
    case TK::ProgramCounterIndexKind: {
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7;
        bool an = (ew >> 15) & 1;
        bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        return fmt::format("recomp_mem_write{}((0x{:06X}U + {}({}) + (int32_t){}) & 0xFFFFFFU, (uint{}_t)({}));",
                           bits, sea, xcast, xr, (int)d8, bits, val);
    }
    default:
        return fmt::format("/* unimplemented write {} */", val);
    }
}

std::string Lifter::pre_effect(const m68k::Target& t, int bytes) const {
    if (t.kind() != TK::AddressDecrementKind) return "";
    int idx = t.index();
    int adj = (idx == 7 && bytes == 1) ? 2 : bytes;
    return fmt::format("ctx.a[{}] -= {}; ", idx, adj);
}

std::string Lifter::post_effect(const m68k::Target& t, int bytes) const {
    if (t.kind() != TK::AddressIncrementKind) return "";
    int idx = t.index();
    int adj = (idx == 7 && bytes == 1) ? 2 : bytes;
    return fmt::format(" ctx.a[{}] += {};", idx, adj);
}

std::string Lifter::ea_expr(const m68k::Target& t, uint32_t sea, uint32_t pc_after) const {
    const int idx = t.index();
    switch (t.kind()) {
    case TK::AddressKind:
    case TK::AddressIncrementKind:
    case TK::AddressDecrementKind:
        return fmt::format("ctx.a[{}]", idx);
    case TK::AddressDisplacementKind:
        return fmt::format("(ctx.a[{}] + (int32_t)(int16_t)0x{:04X}U) & 0xFFFFFFU",
                           idx, t.get_ext_word0());
    case TK::AddressIndexKind: {
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7; bool an = (ew >> 15) & 1; bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        return fmt::format("(ctx.a[{}] + {}({}) + (int32_t){}) & 0xFFFFFFU",
                           idx, xcast, xr, (int)d8);
    }
    case TK::ProgramCounterDisplacementKind:
    case TK::AbsoluteShortKind:
    case TK::AbsoluteLongKind:
        return fmt::format("0x{:06X}U", sea);
    case TK::ProgramCounterIndexKind: {
        uint16_t ew = t.get_ext_word0();
        int xn = (ew >> 12) & 7; bool an = (ew >> 15) & 1; bool xl = (ew >> 11) & 1;
        int8_t d8 = (int8_t)(ew & 0xFF);
        uint32_t base = pc_after - 2;
        std::string xr = an ? fmt::format("ctx.a[{}]", xn) : fmt::format("ctx.d[{}]", xn);
        std::string xcast = xl ? "(int32_t)" : "(int32_t)(int16_t)";
        return fmt::format("(0x{:06X}U + {}({}) + (int32_t){}) & 0xFFFFFFU",
                           base, xcast, xr, (int)d8);
    }
    default:
        return "0 /* unknown EA */";
    }
}

uint32_t Lifter::static_ea(const m68k::Target& t, uint32_t pc_after) const {
    switch (t.kind()) {
    case TK::AbsoluteLongKind:
        return ((uint32_t)t.get_ext_word0() << 16) | t.get_ext_word1();
    case TK::AbsoluteShortKind:
        return (uint32_t)(int32_t)(int16_t)t.get_ext_word0();
    case TK::ProgramCounterDisplacementKind:
        return (uint32_t)((int32_t)pc_after - 2 + (int16_t)t.get_ext_word0());
    default:
        return 0;
    }
}

const char* Lifter::cond_expr(m68k::Instruction::Condition c) {
    switch (c) {
    case IC::TrueCond:           return "1";
    case IC::FalseCond:          return "0";
    case IC::HigherCond:         return "(!ctx.sr.c && !ctx.sr.z)";
    case IC::LowerOrSameCond:    return "(ctx.sr.c || ctx.sr.z)";
    case IC::CarryClearCond:     return "(!ctx.sr.c)";
    case IC::CarrySetCond:       return "(ctx.sr.c)";
    case IC::NotEqualCond:       return "(!ctx.sr.z)";
    case IC::EqualCond:          return "(ctx.sr.z)";
    case IC::OverflowClearCond:  return "(!ctx.sr.v)";
    case IC::OverflowSetCond:    return "(ctx.sr.v)";
    case IC::PlusCond:           return "(!ctx.sr.n)";
    case IC::MinusCond:          return "(ctx.sr.n)";
    case IC::GreaterOrEqualCond: return "(ctx.sr.n == ctx.sr.v)";
    case IC::LessThanCond:       return "(ctx.sr.n != ctx.sr.v)";
    case IC::GreaterThanCond:    return "(!ctx.sr.z && ctx.sr.n == ctx.sr.v)";
    case IC::LessOrEqualCond:    return "(ctx.sr.z || ctx.sr.n != ctx.sr.v)";
    default:                     return "0";
    }
}

uint32_t Lifter::rom_read(uint32_t addr, int bytes) const {
    uint32_t val = 0;
    for (int i = 0; i < bytes; ++i)
        val = (val << 8) | ((addr + i < rom_.size()) ? rom_[addr + i] : 0);
    return val;
}

std::string Lifter::areg(int n) {
    return fmt::format("ctx.a[{}]", n);
}
